# Generated by Django 5.0.6 on 2025-06-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='seats_booked',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='theater',
            name='total_seats',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
