# Generated by Django 5.0.6 on 2025-06-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_theater_seats_booked_theater_total_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='seats_booked',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='total_seats',
        ),
    ]
