# Generated by Django 5.0.6 on 2025-06-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_genre_movie_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
